default: &default
  additional_paths:
  - /Users/qinmingyuan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activestorage-6.1.3/app/assets/javascripts
  - /Users/qinmingyuan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actioncable-6.1.3/app/assets/javascripts
  - /Users/qinmingyuan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actionmailbox-6.1.3/app/views
  - /Users/qinmingyuan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actiontext-6.1.3/app/views
  - /Users/qinmingyuan/work/engine/rails_com/app/packs/images
  - /Users/qinmingyuan/work/engine/rails_com/app/views
  - /Users/qinmingyuan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/kaminari-core-1.2.1/app/views
  engine_paths:
  - /Users/qinmingyuan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actionmailbox-6.1.3/app/views
  - /Users/qinmingyuan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actiontext-6.1.3/app/views
  - /Users/qinmingyuan/work/engine/rails_com/app/views
  - /Users/qinmingyuan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/kaminari-core-1.2.1/app/views
development:
  <<: *default
  public_output_path: packs-dev
  dev_server:
    disableHostCheck: true
    headers:
      Access-Control-Allow-Headers: x-csrf-token, x-requested-with
test:
  <<: *default
  public_output_path: packs-test
staging:
  <<: *default
  compile: false
  cache_manifest: true
production:
  <<: *default
  compile: false
